In [1]:
import numpy as np
import pandas as pd

In [2]:
ruta = "C:\medallas.csv"
df = pd.read_csv(ruta)

df

     Oro  Plata  Bronce  Total          Pais
0    NaN    1.0     2.0      3     Argentina
1    NaN    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    NaN    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   NaN    1.0     NaN      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    NaN     2.0      5    Uzbekistan
92   1.0    3.0     NaN      4     Venezuela

[93 rows x 5 columns]

In [3]:
df.head()

    Oro  Plata  Bronce  Total        Pais
0   NaN    1.0     2.0      3   Argentina
1   NaN    2.0     2.0      4     Armenia
2  17.0    7.0    22.0     46   Australia
3   1.0    1.0     5.0      7     Austria
4   NaN    3.0     4.0      7  Azerbaijan

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [5]:
df.describe()

             Oro      Plata     Bronce       Total
count  65.000000  69.000000  76.000000   93.000000
mean    4.400000   4.768116   4.934211   10.548387
std     7.633806   7.276362   6.261705   18.897617
min     1.000000   1.000000   1.000000    1.000000
25%     1.000000   1.000000   1.000000    2.000000
50%     2.000000   2.000000   2.000000    4.000000
75%     3.000000   5.000000   5.250000    8.000000
max    39.000000  41.000000  33.000000  113.000000

In [ ]:


temperatura = df['Temperatura'].to_numpy()
precipitacion = df['Precipitación'].to_numpy()
humedad = df['Humedad'].to_numpy()

temperatura