In [1]:
#CARGA, VALIDACION E INSPECCION
#PUNTO 1
import numpy as np
import pandas as pd

In [2]:
#PUNTO 1
ruta = "C:\Lluvias_Region_A.csv"
df = pd.read_csv(ruta)

df

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,A CORUNA,240.5,293.4,31.0,80.6,149.5,108.9,44.6,21.8,96.5,154.5,100.8,214.8,1536.9
1,ALBACETE,68.1,28.0,26.2,65.3,25.4,50.0,2.0,34.5,48.0,44.8,33.1,14.1,439.5
2,ALICANTE,49.2,3.7,63.2,85.8,57.2,20.0,9.2,5.0,44.0,41.1,47.4,1.8,427.6
3,ALMERIA,56.3,5.2,35.8,43.1,38.8,16.9,10.2,1.9,17.4,27.3,32.6,3.2,288.7
4,ARABA,96.8,79.9,38.0,52.0,37.7,107.8,8.5,17.7,63.3,38.5,212.2,197.3,949.7
5,ASTURIAS,196.9,138.4,34.4,73.1,67.4,131.2,22.5,19.2,90.3,74.2,309.8,205.3,1362.7
6,AVILA,67.6,104.5,5.6,83.4,25.7,44.4,5.5,14.2,97.9,91.7,33.9,47.5,621.9

In [3]:
#PUNTO 2 (SOLO QUE ACA MUESTRA EN TODAS LAS COLUMNAS, NO EN UNA ESPECIFICA.)
df.isnull() #Aqui visualizamos de una diferente manera los datos nulos, donde hay un True hay un nulo

,region,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [5]:
#PUNTO 3
df.describe()

,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,anual
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,110.771429,93.300000,33.457143,69.042857,57.385714,68.457143,14.642857,16.328571,65.342857,67.442857,109.971429,97.714286,803.857143
std,76.251376,102.007255,17.060564,16.403542,43.484458,46.629385,14.661157,10.888176,30.856056,44.476206,109.593076,102.344507,490.535109
min,49.200000,3.700000,5.600000,43.100000,25.400000,16.900000,2.000000,1.900000,17.400000,27.300000,32.600000,1.800000,288.700000
25%,61.950000,16.600000,28.600000,58.650000,31.700000,32.200000,7.000000,9.600000,46.000000,39.800000,33.500000,8.650000,433.550000
50%,68.100000,79.900000,34.400000,73.100000,38.800000,50.000000,9.200000,17.700000,63.300000,44.800000,47.400000,47.500000,621.900000
75%,146.850000,121.450000,36.900000,82.000000,62.300000,108.350000,16.350000,20.500000,93.400000,82.950000,156.500000,201.300000,1156.200000
max,240.500000,293.400000,63.200000,85.800000,149.500000,131.200000,44.600000,34.500000,97.900000,154.500000,309.800000,214.800000,1536.900000

In [10]:
#FILTRADO Y SELECCION
#PUNTO 4
julio = df['julio'].to_numpy()
agosto = df['agosto'].to_numpy()
julio

array([44.6,  2. ,  9.2, 10.2,  8.5, 22.5,  5.5])

In [18]:
# Identificar el promedio de cada array
np.where ((np.isnan(julio), agosto))
resultados = pd.DataFrame({
    'Metrica': ['julio', 'agosto'],
    'Valor': [julio, agosto]
})

# Guardar los resultados en un nuevo archivo CSV
resultados.to_csv('df_verano_seco.csv', index=False)